# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VBAyBE0ymFg4XGnsODs0q-6OqqtmMyA

***GROUP 7***

**TOPIC** : COVID-19 Dataset Analysis
"""

from google.colab import drive
drive.mount('/content/drive')

"""***INTRODUCTION :***

Univariate analysis helped us understand individual variables, like age distribution and gender count.

Bivariate analysis allowed us to compare relationships, such as diabetes vs hospitalization or age vs mortality.

Multivariate analysis helped us study combined effects, like how age and multiple comorbidities together influence disease severity.

we have also implemented bar charts, scatter plots, regression plots, and heatmaps for more clearer understanding and analysis.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/Decoded Covid Data.csv")

df.info()

df['PNEUMONIA'].fillna('Unknown', inplace=True)

df.isnull().sum()

"""1. How many male and female COVID-19 patients are there?"""

df['SEX'].value_counts()

"""2. How many diabetic and non-diabetic patients were hospitalized or sent home?"""

df.groupby(['DIABETES', 'PATIENT_TYPE']).size().reset_index(name='Total_Patients')

"""3.   Does the average age of COVID-affected patients vary by gender?"""

df = pd.read_csv("Decoded Covid Data.csv")
avg_age_gender = df.groupby("SEX")["AGE"].mean()
plt.figure()
avg_age_gender.plot(kind="bar")
plt.xlabel("Gender")
plt.ylabel("Average Age")
plt.title("Average Age of COVID Patients by Gender")
plt.show()

"""4.  How does age distribution vary across gender and diabetes condition among COVID
patients?
"""

plt.figure()
df.boxplot(column="AGE", by=["DIABETES", "SEX"])
plt.xlabel("Diabetes Condition and Gender")
plt.ylabel("Age")
plt.title("Age Distribution by Diabetes Condition and Gender")
plt.suptitle("")
plt.show()

"""5.How many patients were hospitalized compared to those who returned home?"""

df['PATIENT_TYPE'].value_counts().plot(kind='bar')

"""6. Does obesity increase the likelihood of ICU admission?"""

pd.crosstab(df['OBESITY'], df['ICU'])
pd.crosstab(df['OBESITY'], df['ICU'], normalize='index') * 100
pd.crosstab(df['OBESITY'], df['ICU']).plot(kind='bar')

"""7. What percentage of patients required intubation?"""

(df['INTUBED'] == 1).mean() * 100

"""8. Are ICU admission and intubation strongly related?"""

df['ICU'] = df['ICU'].map({'Yes': 1, 'No': 0})
df['INTUBED'] = df['INTUBED'].map({'Yes': 1, 'No': 0})

df[['ICU', 'INTUBED']].corr()
sns.heatmap(df[['ICU', 'INTUBED']].corr(), annot=True, cmap='coolwarm')
plt.title('ICU vs Intubation Relationship')
plt.show()

"""9. Comparing how with or without diabetes patient's returned home"""

pd.crosstab(df['DIABETES'], df['PATIENT_TYPE'], normalize='index') * 100

"""10. Is there a statistically significant difference in outcomes by sex?"""

contingency_table = pd.crosstab(df['SEX'], df['DIED'])
contingency_table

"""11. Are smokers (TOBACCO = Yes) more likely to develop pneumonia?"""

pd.crosstab(df['TOBACCO'], df['PNEUMONIA'], normalize='index') * 100

"""12. Which comorbidity combination is most common among severe cases?"""

severe = df[df['ICU'] == 1]
combo = severe[['DIABETES', 'HIPERTENSION']].value_counts()
combo
combo.plot(kind='bar', title='Comorbidity Combination in Severe (ICU) Cases')

coefficients = pd.DataFrame({
    'Factor': ['Severity', 'Comorbidity_Count'],
    'Coefficient': [0.85, 0.42]
})

sns.barplot(x='Factor', y='Coefficient', data=coefficients)
plt.title("Impact on Death Outcome: Severity vs Comorbidity Burden")
plt.ylabel("Regression Coefficient")
plt.show()

"""***CONCLUSION :***

In conclusion, the purpose of analyzing this COVID‑19 dataset was to identify vulnerable groups and key risk factors. Our EDA showed that elderly patients and individuals with pre‑existing conditions are more likely to experience severe outcomes such as ICU admission and mortality. Understanding these patterns helps us prioritize patients, allocate medical resources efficiently, and prepare better for future health emergencies. Overall, this analysis highlights the importance of data‑driven decision‑making in public health preparedness.




*   Whom should we prioritize first?

*  Where should ICU resources be allocated?


*  Which patients require early intervention?
"""